### ISSUE TITLE
Create tests for duplicate points and duplicate angles

### ISSUE THREAD

**Issue by Spezzdidly** [Spezzdidly/ChansAlgorithm#3]

**Comment by sjohns3404** [comment]
Now that removing duplicate points is done, I only need to implement removing the duplicate polar angles and then I can finish this issue. I updated the milestone for tomorrow but I am pretty sure this will be completed by tonight, I will run the test cases and then I will be able to start working on partitioning and other aspects of Chan's Algorithm.
